FROM archlinux/base
RUN \
 pacman -Sy --noconfirm cmake gcc make
RUN mkdir -p /usr/src/symbol_export_test
WORKDIR /usr/src/symbol_export_test
COPY CMakeLists.txt main.cpp shared.cpp shared.h symbols.map test_compiler.sh ./
